# Generated by Django 4.2.9 on 2024-01-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('telegram_chat_id', models.CharField(max_length=30, verbose_name='Телеграмм')),
                ('telegram_nickname', models.CharField(max_length=30, verbose_name='Ник в телеграме')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('telegram', models.CharField(max_length=30, verbose_name='Телеграмм')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название салона')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес салона')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон салона')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало смены')),
                ('end_time', models.DateTimeField(verbose_name='Конец смены')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='beautyshop_bot.salon', verbose_name='Салон смены')),
            ],
            options={
                'verbose_name': 'Смены',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(verbose_name='Начало записи')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='beautyshop_bot.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='beautyshop_bot.master', verbose_name='Мастер')),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyshop_bot.speciality', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='speciality',
            field=models.ManyToManyField(to='beautyshop_bot.speciality', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='master',
            name='working_hours',
            field=models.ManyToManyField(related_name='master', to='beautyshop_bot.timeslot', verbose_name='Смены'),
        ),
    ]
